[book]
title = "WebIridium User Manual"
authors = ["Dan Nguyen", "Long Nguyenle"]
language = "en"

[output.html]
default-theme = "iridium-light"
preferred-dark-theme = "iridium-dark"
git-repository-url = "https://github.com/sys-bio/WebIridium"
edit-url-template = "https://github.com/sys-bio/WebIridium/edit/main/manual/{path}"
site-url = "WebIridium/manual/"
additional-css = ["theme/img-white-background.css"]